from stvm import VM

vm = VM()
# vm.open_image("bootstrap.image")
# vm.open_image("bootstrap2.image")
# vm.open_image("bootstrap3.image")
# vm.open_image("bootstrap-benchmark.image")
# vm.open_image("bootstrap-fib.image")
# vm.open_image("bootstrap-fib2.image")
# vm.open_image("bootstrap-fib3.image")
# vm.open_image("bootstrap-fib4.image")
vm.open_image("bootstrap-fib5.image")
# vm.open_image("bootstrap-fib6.image")  # 20
# vm.open_image("bootstrap-nonlocal.image")
# vm.open_image("bootstrap-loop.image")
# vm.open_image("bootstrap-block.image")
# vm.open_image("bootstrap-symbol.image")
# vm.open_image("bootstrap-symbol2.image")
# vm.open_image("bootstrap-select.image")
# vm.open_image("bootstrap-todo.image")
# vm.open_image("bootstrap-value.image")
# vm.open_image("bootstrap-smallint.image")
# vm.open_image("minimal-pharo.image")
# vm.open_image("tmp/Pharo.image")
# vm.open_image("Pharo-32.image")
# vm.open_image("Pharo.image")

vm.execute()
